---
- hosts: all

  tasks:
    - name: get environment variables
      shell: env | sort
      register: shell_environment

    - name: show environment variables
      debug:
        var: shell_environment

    - name: find .boto
      shell: find ~ -name .boto
      ignore_errors: True

    - name: find .aws
      shell: find ~ -name .aws
      ignore_errors: True
