---
- hosts: all

  tasks:
    - name: get environment variables
      shell: env | sort
      register: shell_environment

    - name: show environment variables
      debug:
        var: shell_environment

    - name: show aws credentials
      shell: cat ~/.aws/credentials
      ignore_errors: True

    - name: show file list
      shell: ls -lart
